### ISSUE TITLE
[Question] - Good nitro servers?

### ISSUE THREAD

**Issue by HydraX4** [PeterStrick/NitroSniperGUI#7]
Hello! I am new to this program. What are good servers to join to get free nitro with the sniper?

thanks!!!

**Comment by PeterStrick** [comment]
Generally, I would join Emoji/Giveaway/Bot Developer Servers that have a big user base. You could also try Official Servers from Game Companies and others.

**Comment by HydraX4** [comment]
okay thanks, is it possible to host this on a linux machine?

**Comment by PeterStrick** [comment]
> okay thanks, is it possible to host this on a linux machine?

Well, I used to develop a release that was compatible with Wine but stopped doing so, because of incompatibilities and because I don´t possess a Linux Machine at the moment. But, you can run the [Go Nitro Sniper](https://github.com/Vedzaa/NitroSniperGo) on Linux just fine by installing [Golang](https://golang.org/doc/install). It may be a tedious process but should work nevertheless.

**Comment by PeterStrick** [comment]
> > okay thanks, is it possible to host this on a linux machine?
> 
> Well, I used to develop a release that was compatible with Wine but stopped doing so, because of incompatibilities and because I don´t possess a Linux Machine at the moment. But, you can run the [Go Nitro Sniper](https://github.com/Vedzaa/NitroSniperGo) on Linux just fine by installing [Golang](https://golang.org/doc/install). It may be a tedious process but should work nevertheless.

Or you can try to get its Linux Release to work

**Comment by PeterStrick** [comment]
@HydraX4 I´ll close this issue then, alright? If you have more questions, just write them.
